[package]
name = "poker"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.7.1"
thiserror = "1.0.39"

[dev-dependencies]
md-5 = "0.10.5"
hex-literal = "0.3.4"
criterion = "0.4.0"

[[bench]]
name = "evaluate"
harness = false
